version: "2"
services:
  postgresql:
    container_name: postgres
    image: postgres:9-alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=some_user
      - POSTGRES_PASSWORD=some_passwd
      - POSTGRES_DB=some_db
